package Ubuntu::Releases;

use 5.010001;
use strict;
use warnings;

use Perinci::Sub::Gen::AccessTable qw(gen_read_table_func);

use Exporter;
our @ISA = qw(Exporter);
our @EXPORT_OK = qw(
                       list_ubuntu_releases
               );

our %SPEC;

# VERSION
# DATE

# BEGIN FRAGMENT id=meta
# note: This section is generated by a script. Do not edit manually!
# src-file: /mnt/home/s1/repos/gudangdata/table/ubuntu_release/meta.yaml
# src-revision: 1c3da55a6f41b422b2a7803eb408c04526fb9e76
# revision-date: Tue May 27 17:45:03 2014 +0700
# generate-date: Wed May 28 11:12:30 2014
# generated-by: /mnt/home/s1/repos/gudangdata/bin/gen-perl-meta-snippet
our $meta = {
  fields => {
    code_name       => {
                         index    => 1,
                         schema   => "str*",
                         sortable => 1,
                         summary  => "Code name",
                         unique   => 1,
                       },
    kernelver       => { index => 5, schema => "str*", sortable => 1, summary => "Kernel version" },
    reldate         => { index => 2, schema => "date*", sortable => 1, summary => "Release date" },
    supdate_desktop => {
                         index    => 3,
                         schema   => "date*",
                         sortable => 1,
                         summary  => "Supported until (for desktop)",
                       },
    supdate_server  => {
                         index    => 4,
                         schema   => "date*",
                         sortable => 1,
                         summary  => "Supported until (for servers)",
                       },
    version         => { index => 0, schema => "str*", sortable => 1, summary => "Version", unique => 1 },
  },
  pk => "version",
  summary => "Ubuntu releases",
};
# END FRAGMENT id=meta
# BEGIN FRAGMENT id=data
# note: This section is generated by a script. Do not edit manually!
# src-file: /mnt/home/s1/repos/gudangdata/table/ubuntu_release/data.csv
# src-revision: 1c3da55a6f41b422b2a7803eb408c04526fb9e76
# revision-date: Tue May 27 17:45:03 2014 +0700
# generate-date: Wed May 28 11:12:30 2014
# generated-by: /mnt/home/s1/repos/gudangdata/bin/gen-perl-data-snippet
our $data = [
    ['4.10','Warty Warthog','2004-10-20','2006-04-30','2006-04-30','2.6.8'],
    ['5.04','Hoary Hedgehog','2005-04-08','2006-10-31','2006-10-31','2.6.10'],
    ['5.10','Breezy Badger','2005-10-13','2007-04-13','2007-04-13','2.6.12'],
    ['6.06 LTS','Dapper Drake','2006-06-01','2009-07-14','2011-06-01','2.6.15'],
    ['6.10','Edgy Eft','2006-10-26','2008-04-25','2008-04-25','2.6.17'],
    ['7.04','Feisty Fawn','2007-04-19','2008-10-19','2008-10-19','2.6.20'],
    ['7.10','Gutsy Gibbon','2007-10-18','2009-04-18','2009-04-18','2.6.22'],
    ['8.04 LTS','Hardy Heron','2008-04-24','2011-05-12','2013-05-09','2.6.24'],
    ['8.10','Intrepid Ibex','2008-10-30','2010-04-30','2010-04-30','2.6.27'],
    ['9.04','Jaunty Jackalope','2009-04-23','2010-10-23','2010-10-23','2.6.28'],
    ['9.10','Karmic Koala','2009-10-29','2011-04-30','2011-04-30','2.6.31'],
    ['10.04 LTS','Lucid Lynx','2010-04-29','2013-05-09','2015-04-30','2.6.32'],
    ['10.10','Maverick Meerkat','2010-10-10','2012-04-10','2012-04-10','2.6.35'],
    ['11.04','Natty Narwhal','2011-04-28','2012-10-28','2012-10-28','2.6.38'],
    ['11.10','Oneiric Ocelot','2011-10-13','2013-05-09','2013-05-09','3.0'],
    ['12.04 LTS','Precise Pangolin','2012-04-26','2017-04-26','2017-04-26','3.2'],
    ['12.10','Quantal Quetzal','2012-10-18','2014-05-16','2014-05-16','3.5'],
    ['13.04','Raring Ringtail','2013-04-25','2014-01-27','2014-01-27','3.8'],
    ['13.10','Saucy Salamander','2013-10-17','2014-07-31','2014-07-31','3.11'],
    ['14.04 LTS','Trusty Tahr','2014-04-17','2019-04-30','2019-04-30','3.13'],
    ['14.10','Utopic Unicorn','2014-10-16','2015-07-31','',''],
]
;
# END FRAGMENT id=data

my $res = gen_read_table_func(
    name => 'list_ubuntu_releases',
    table_data => $data,
    table_spec => $meta,
    #langs => ['en_US', 'id_ID'],
);
die "BUG: Can't generate func: $res->[0] - $res->[1]" unless $res->[0] == 200;

1;
# ABSTRACT: List Ubuntu releases

=head1 SYNOPSIS


=head1 DESCRIPTION

This module contains list of Ubuntu releases. Data source is currently at:
https://github.com/sharyanto/gudangdata (table/ubuntu_release).


=head1 SEE ALSO

L<Debian::Releases>

=cut
